### ISSUE TITLE
Jitpack: Could not find msg-simple.jar (com.github.fge:msg-simple:1.1)

### ISSUE THREAD

**Issue by Allen-cxl** [java-json-tools/json-schema-validator#330]
gradle run error，event log sow could not find msg-simple.jar (com.github.fge:msg-simple:1.1)

**Comment by Capstan** [comment]
Have you tried using the wrapper `./gradlew`? Does it have the same error?

**Comment by Capstan** [comment]
In any case, please re-open with invocation details and logs if it does.

**Comment by Allen-cxl** [comment]
use the wrapper 
![feg_error](https://user-images.githubusercontent.com/13672113/69685585-e4cf9f80-10f7-11ea-8af7-0637a6848833.png)

**Comment by Allen-cxl** [comment]
https://jitpack.io/#fge/msg-simple  status error, whether it's related to it

**Comment by Capstan** [comment]
It does appear that Jitpack doesn't have a copy of msg-simple v1.1. That said, there isn't anything in the `*.gradle` files that references Jitpack instead of [MavenCentral](https://github.com/java-json-tools/json-schema-validator/blob/master/build.gradle#L52), so have you customized your build? I have no idea whether or not @fge did any explicit pushing to Jitpack in addition to MavenCentral, but I'm about to release a msg-simple v1.2 from [java-json-tools/msg-simple](https://github.com/java-json-tools/msg-simple) and I do not plan to do anything special for Jitpack.
