### ISSUE TITLE
Using JSON schema with an array of mixed object types

### ISSUE THREAD

**Issue by ettig** [java-json-tools/json-schema-validator#46]
as far as I understand - this should be a valid schema:

{ 
  "type" : "array",
  "items" : { 
     "type" : [ 
       { "type" : "object", "properties" : { "name" : { "type" : "string" }}},
       { "type" : "object", "properties" : { "price" : { "type" : "number" } } }
    ]
  }
}

but it comes out as invalid in the schema validator
is this a bug? or it's actually invalid?
thanks!

**Comment by agapare** [comment]
Hi guys, I need help build a json schema from the sample below:

{
  "1453235400": {
    "ERRORS_OUT": null,
    "OCTETS_OUT": 232.957375822694,
    "PACKETS_OUT": 1.8996969225584,
    "DISCARDS_OUT": null,
    "SPEED": 2048000,
    "DISCARDS_IN": null,
    "PACKETS_IN": 1.86311703463372,
    "OCTETS_IN": 238.160971788575,
    "ERRORS_IN": null,
    "IFSTATUS": 1
  },
  "1453235700": {
    "ERRORS_OUT": null,
    "OCTETS_OUT": 231.133641048357,
    "PACKETS_OUT": 1.88395658914729,
    "DISCARDS_OUT": null,
    "SPEED": 2048000,
    "DISCARDS_IN": null,
    "PACKETS_IN": 1.84730778885197,
    "OCTETS_IN": 236.086393503138,
    "ERRORS_IN": null,
    "IFSTATUS": 1
  },
  "1453236000": {
    "ERRORS_OUT": null,
    "OCTETS_OUT": 230.8488,
    "PACKETS_OUT": 1.88284444444444,
    "DISCARDS_OUT": null,
    "SPEED": 2048000,
    "DISCARDS_IN": null,
    "PACKETS_IN": 1.84617777777778,
    "OCTETS_IN": 235.842177777778,
    "ERRORS_IN": null,
    "IFSTATUS": 1
  }
}

**Comment by huggsboson** [comment]
@agapare You should start a new issue for this... it should be pretty doable but I'm going to need 20 free minutes to work it out.

**Comment by tigerqiu712** [comment]
this issue was fixed ?
{
"1453235400": {
"ERRORS_OUT": null,
"OCTETS_OUT": 232.957375822694,
"PACKETS_OUT": 1.8996969225584,
"DISCARDS_OUT": null,
"SPEED": 2048000,
"DISCARDS_IN": null,
"PACKETS_IN": 1.86311703463372,
"OCTETS_IN": 238.160971788575,
"ERRORS_IN": null,
"IFSTATUS": 1
},
"1453235700": {
"ERRORS_OUT": null,
"OCTETS_OUT": 231.133641048357,
"PACKETS_OUT": 1.88395658914729,
"DISCARDS_OUT": null,
"SPEED": 2048000,
"DISCARDS_IN": null,
"PACKETS_IN": 1.84730778885197,
"OCTETS_IN": 236.086393503138,
"ERRORS_IN": null,
"IFSTATUS": 1
},
"1453236000": {
"ERRORS_OUT": null,
"OCTETS_OUT": 230.8488,
"PACKETS_OUT": 1.88284444444444,
"DISCARDS_OUT": null,
"SPEED": 2048000,
"DISCARDS_IN": null,
"PACKETS_IN": 1.84617777777778,
"OCTETS_IN": 235.842177777778,
"ERRORS_IN": null,
"IFSTATUS": 1
}
}
